services:
  - type: web
    name: kingdom-of-harpoon
    env: node
    plan: free
    buildCommand: npm ci && NODE_ENV=production npm run build:full
    startCommand: NODE_ENV=production node dist/server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
    autoDeploy: true
