services:
  - type: web
    name: kingdom-of-harpoon
    env: node
    plan: free
    buildCommand: npm install && npm run build:full
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
    autoDeploy: true